language: go

go:
  - "1.x"
  - "1.8"
  - "1.9"
  - "1.10.3"
  - "1.10.x"
  - master

script:
  - go test -coverprofile="coverage.txt" -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
