language: go

go:
  - "1.x"
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - "1.12"
  - "1.13"
  - "1.13.8"
  - master

script:
  - go test -coverprofile="coverage.txt" -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
