name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Build
      run: go build -v ./...
    - env:
        MSGraphTenantID: ${{ secrets.MSGraphTenantID }}:
        MSGraphApplicationID: ${{ secrets.MSGraphApplicationID }}:
        MSGraphClientSecret: ${{ secrets.MSGraphClientSecret }}:
        MSGraphExistingGroupDisplayName: ${{ secrets.MSGraphExistingGroupDisplayName }}:
        MSGraphExistingUserPrincipalInGroup: ${{ secrets.MSGraphExistingUserPrincipalInGroup }}
    - name: Test
      run: go test -v ./...
